#? Config file for btop v. 1.4+

color_theme = "noir"
theme_background = False
truecolor = True
vim_keys = False
rounded_corners = True
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1000
proc_sorting = "cpu lazy"
proc_tree = False
proc_gradient = True
cpu_single_graph = False
show_uptime = True
check_temp = True
show_coretemp = True
temp_scale = "celsius"
show_battery = True
show_disks = True
only_physical = True
io_mode = False
base_10_sizes = False
